"""empty message

Revision ID: 9013a65de54e
Revises: c320d547f8f6
Create Date: 2020-03-02 19:40:35.918265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9013a65de54e'
down_revision = 'c320d547f8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('click_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'click_num')
    # ### end Alembic commands ###
