"""empty message

Revision ID: c320d547f8f6
Revises: 
Create Date: 2020-03-02 12:34:44.763193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c320d547f8f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('bid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category1', sa.String(length=30), nullable=True),
    sa.Column('category2', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('picture', sa.String(length=300), nullable=True),
    sa.Column('content', sa.String(length=3000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('detail',
    sa.Column('did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('reply',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=3000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('reply')
    op.drop_table('detail')
    op.drop_table('article')
    # ### end Alembic commands ###
